-- AlterTable
ALTER TABLE "Host" ADD COLUMN "aptUpdateCount" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Host" ADD COLUMN "aptCheckedAt" TIMESTAMP(3);
ALTER TABLE "Host" ADD COLUMN "aptNotifiedCount" INTEGER NOT NULL DEFAULT 0;
